import React from "react";
import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom";
import "./App.css";

function Home() {
  return (
    <div className="page home">
      <h1>Welcome to AmigoLocal</h1>
      <p>
        AmigoLocal is a privacy-first app that runs the 3n Gemma model locally
        on your iPad and iPhone. No data leaves your device.
      </p>
      <div className="screenshots">
        <h2>App Screenshots</h2>
        <div className="screenshot-row">
          <img
            src="/ipadscreenshot.png"
            alt="iPad screenshot"
            style={{ width: 200, marginRight: 20 }}
          />
          <img
            src="/Iphonescreenshot.png"
            alt="iPhone screenshot"
            style={{ width: 120 }}
          />
        </div>
      </div>
      <div className="whats-next">
        <h2>What's Next?</h2>
        <p>We will add images and audio features soon. Stay tuned!</p>
      </div>
    </div>
  );
}

function Privacy() {
  const termsText = `Privacy Policy & Terms of Use

Your privacy is important to us. AmigoLocal processes all data locally on your device. No conversations or personal data are sent to external servers.

By using AmigoLocal, you agree to:
- Use the app for lawful purposes only.
- Not attempt to reverse engineer or misuse the app.
- Accept that AmigoLocal is provided as-is, without warranty.

Disclaimer: AmigoLocal strives to provide accurate and helpful information, but it may not always be correct. The responses you receive are generated by an AI model and should not be considered professional advice. Always double-check important details and consult a qualified expert when necessary. AmigoLocal is constantly learning and improving, but errors and misunderstandings can still occur. Use your own judgment and verify information before making decisions based on AmigoLocal's suggestions.`;

  return (
    <div className="page privacy">
      <h1>Privacy Policy & Terms of Use</h1>
      <pre
        style={{
          whiteSpace: "pre-wrap",
          fontFamily: "inherit",
          lineHeight: "1.6",
        }}
      >
        {termsText}
      </pre>
    </div>
  );
}

function Support() {
  return (
    <div className="page support">
      <h1>Support</h1>
      <p>
        For support, contact us at{" "}
        <a href="mailto:redcalf2007@gmail.com">redcalf2007@gmail.com</a>
      </p>
    </div>
  );
}

function App() {
  return (
    <Router>
      <nav className="navbar">
        <Link to="/">Home</Link>
        <Link to="/privacy">Privacy</Link>
        <Link to="/support">Support</Link>
      </nav>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/privacy" element={<Privacy />} />
        <Route path="/support" element={<Support />} />
      </Routes>
    </Router>
  );
}

export default App;
